---
ungrouped:
  hosts:
    192.168.100.52:
      ansible_user: noahb
      ansible_password: 
    192.168.250.1:
      ansible_user: root
      ansible_password: 
    

winservers:
  hosts:
    192.168.50.51:
      ansible_user: Administrator
      ansible_password: !
    192.168.50.52:
      ansible_user: Administrator
      ansible_password: !

localhosts:
  hosts:
    127.0.0.1:
      ansible_user: nrbauer
      ansible_password:

dnspi:
  hosts:
    192.168.1.20:
      ansible_user: noahpi
      ansible_password:

nmspi:
  hosts:
    192.168.1.25:
      ansible_user: noahsnmp
      ansible_password:

pvenms:
  hosts:
    192.168.150.51:
      ansible_user: noahsnmp
      ansible_password:
    192.168.150.52:
      ansible_user: noahsnmp
      ansible_password:
    192.158.150.53:
      ansible_user: noahsnmp
      ansible_password:
