services:
  # Zabbix database
  zabbix-db:
    container_name: zabbix-db
    image: zabbix/zabbix-server-mysql
    restart: always
    volumes:
      - /var/lib/zabbix/snmptraps
    environment:
      - MYSQL_USER=${MySQL_User}
      - MYSQL_PASSWORD=${MySQL_pass}
      - MYSQL_ROOT_PASSWORD=${MySQL_root_pass}
      - DB_SERVER_HOST=192.168.65.20
    stop_grace_period: 1m

  # Zabbix server
  zabbix-server:
    container_name: zabbix-server
    image: zabbix/zabbix-web-apache-mysql
    restart: always
    ports:
      - 10051:10051
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - DB_SERVER_HOST=192.168.65.20
      - ZBX_STARTPINGERS=${ZBX_STARTPINGERS}
    depends_on:
      - zabbix-db
    stop_grace_period: 30s
